export const ErrorCode = Object.freeze({
  INVALID_INPUT: 'INVALID_INPUT',
  AGENT_NOT_FOUND: 'AGENT_NOT_FOUND',
  INDEXER_UNAVAILABLE: 'INDEXER_UNAVAILABLE',
  RPC_UNAVAILABLE: 'RPC_UNAVAILABLE',
  DECODE_FAILED: 'DECODE_FAILED',
  MISSING_CREDENTIALS: 'MISSING_CREDENTIALS',
  UNKNOWN: 'UNKNOWN',
});
